import React, { ReactNode } from "react";
import Header from "./components/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Restaurant | Open Table Next JS",
  description: "Generated by Next JS",
};

interface Props {
  children: ReactNode;
}

const RestaurantLayout = ({ children }: Props) => {
  return (
    <main>
      <Header></Header>
      <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
        {children}
      </div>
    </main>
  );
};

export default RestaurantLayout;
